<#
.SYNOPSIS
    Security Baseline Compliance Report Viewer

.DESCRIPTION
    Reads csv reports generated by the baseline security scanning tool and
    provides a (more) user friendly interface for viewing the compliance data
    then Microsoft Excel.

.NOTES
    Author: [DKI] Daniel Ives
#>

Add-Type -AssemblyName System.IO.Compression.FileSystem
Add-Type -AssemblyName System.Windows.Forms

#$DebugPreference = 'Continue'

$ModuleInvocationPath  = [System.IO.Path]::GetDirectoryName($MyInvocation.MyCommand.Definition)
Import-Module "$ModuleInvocationPath\modules\Putty\Putty.psm1" -Prefix Putty
Import-Module "$ModuleInvocationPath\modules\STIGViewer\STIGViewer.psm1"
Import-Module "$ModuleInvocationPath\modules\Compliance\Compliance.psm1" -Prefix Compliance
Import-Module "$ModuleInvocationPath\modules\Device\Device.psm1" -Prefix Device

$OnLoad  = New-Object System.Collections.ArrayList
$OnClose = New-Object System.Collections.ArrayList

###############################################################################
# Window Definition
$MainForm = New-Object System.Windows.Forms.Form
$MainForm.Text          = "Network Operations Sustainment Center"
$MainForm.Size          = New-Object System.Drawing.Size(1200, 600)
$MainForm.StartPosition = [System.Windows.Forms.FormStartPosition]::CenterScreen

$MainForm.Add_Load({
    param($sender, $e)

    # Set proper Z-order
    # -- Must be performed before the handlers of child controls.
    $TabContainer.BringToFront()

    # Execute Child Handlers
    foreach ($handler in $OnLoad) {
        $handler.Load()
    }

    # Discard the OnLoad Handlers (Free Memory)
    # -- These are only ever used once during the initial loading of the graphical
    #    interface.
    $OnLoad.Clear()
})

$MainForm.Add_Closing({
    param($sender, $e)

    # Execute Child OnClose Handlers
    # -- Critical for any sub-components that may need to close network sockets,
    #    free memory, etc...
    foreach ($handler in $OnClose) {
        $handler.Close()
    }
})

###############################################################################
# Main Menu
$Menu = New-Object System.Windows.Forms.MenuStrip
    $Menu.Dock = [System.Windows.Forms.DockStyle]::Top
    $Menu.Name = 'MainMenu'

    $MainForm.MainMenuStrip = $Menu
    [void]$MainForm.Controls.Add($Menu)

###############################################################################
# Base Content Tab Control Container
$TabContainer = New-Object System.Windows.Forms.TabControl
    $TabContainer.Dock = [System.Windows.Forms.DockStyle]::Fill
    
    [void]$MainForm.Controls.Add( $TabContainer )

$ComponentParams = @{
    Window  = $MainForm
    Parent  = $TabContainer
    Menu    = $Menu
    OnLoad  = $OnLoad
    OnClose = $OnClose
}

###############################################################################
# Register Components
[void]$TabContainer.Controls.Add( (Initialize-DeviceComponents @ComponentParams) )
#[void]$Menu.Items.Add( (New-Object System.Windows.Forms.ToolStripSeparator) )
[void]$TabContainer.Controls.Add( (Initialize-ComplianceComponents @ComponentParams) )
#[void]$Menu.Items.Add( (New-Object System.Windows.Forms.ToolStripSeparator) )
Initialize-PuttyComponents $null $null $Menu $OnLoad

###############################################################################
# Open Window
[void]$MainForm.ShowDialog()

$MainForm.Dispose()